apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-flask-app-deployment
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-flask-app
  template:
    metadata:
      labels:
        app: simple-flask-app
    spec:
      containers:
      - name: simple-flask-app
        image: simple-flask-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
