apiVersion: apps/v1
kind: Deployment
metadata:
  name: dropwizard-deployment
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dropwizard
  template:
    metadata:
      labels:
        app: dropwizard
    spec:
      containers:
      - name: dropwizard
        image: provok/dropwizard:example
        ports:
        - containerPort: 80
