apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: metrics
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
    processors:
      batch:
    exporters:
      otlp:
        endpoint: jaeger:14250
        tls:
          insecure: true
      prometheusremotewrite:
        endpoint: http://prometheus:9090/api/v1/write
      debug:
        verbosity: detailed

    service:
      pipelines:
        traces:
          receivers: [ otlp ]
          processors: [ batch ]
          exporters: [ jaeger ]
        metrics:
          receivers: [ otlp ]
          processors: [ batch ]
          exporters: [ prometheusremotewrite ]
        logs:
          receivers: [ otlp ]
          processors: [ batch ]
          exporters: [ debug ]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector-deployment
  namespace: metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector-contrib:0.133.0
        ports:
        - containerPort: 4317
        args:
        - --config=/etc/otel-collector-config.yaml
        volumeMounts:
        - name: otel-collector-config
          mountPath: /etc/otel-collector-config.yaml
          subPath: otel-collector-config.yaml
      volumes:
      - name: otel-collector-config
        configMap:
          name: otel-collector-config
