apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v2.57.0
        ports:
        - containerPort: 9090
        command:
        - --web.enable-remote-write-receiver
        volumes:
        - /dev/null:/prometheus/prometheus.yml
